from typing import Optional

from pydantic import BaseModel

from .classification import ClassificationType
from .process_flow import DirectedAcyclicGraph
from .text_chunk import TextChunkBody, TextChunkEnd, TextChunkStart


class CompleteChatResponse(BaseModel):
    """Complete chat response model.

    Represents a complete response from a chat conversation, containing the
    full response text generated by the conversation system.
    """

    response: str


class CompleteRejectResponse(BaseModel):
    """Complete reject response model.

    Represents a complete rejection response from the conversation system,
    containing the full rejection message when the system declines to respond.
    """

    response: str


class ClassifiedTextChunkStart(TextChunkStart):
    """Classified text chunk start model.

    Extends TextChunkStart to include classification results and additional
    context information for processing classified text streams.
    """

    def __init__(
        self,
        request_id: str,
        node_name: str,
        classification_result: ClassificationType,
        client_name: str,
        user_input: str,
        dag: DirectedAcyclicGraph,
    ):
        """Initialize the classified text chunk start.

        Args:
            request_id (str):
                Unique identifier for the request.
            node_name (str):
                Name of the processing node.
            classification_result (ClassificationType):
                Result of the text classification process.
            client_name (str):
                Name of the client that generated the input.
            user_input (str):
                Original user input text that was classified.
            dag (DirectedAcyclicGraph):
                Directed acyclic graph for workflow management.
        """
        TextChunkStart.__init__(self, request_id, node_name, dag)
        self.classification_result = classification_result
        self.client_name = client_name
        self.user_input = user_input


class ClassifiedTextChunkBody(TextChunkBody):
    """Classified text chunk body model.

    Extends TextChunkBody to handle classified text data within a stream.
    Inherits all functionality from the base TextChunkBody class.
    """

    pass


class ClassifiedTextChunkEnd(TextChunkEnd):
    """Classified text chunk end model.

    Extends TextChunkEnd to include optional DAG information for classified
    text stream completion.
    """

    def __init__(self, request_id: str, dag: Optional[DirectedAcyclicGraph] = None):
        """Initialize the classified text chunk end.

        Args:
            request_id (str):
                Unique identifier for the request.
            dag (Optional[DirectedAcyclicGraph], optional):
                Optional directed acyclic graph for workflow management.
                Defaults to None.
        """
        TextChunkEnd.__init__(self, request_id)
        self.dag = dag


class ConversationChunkStart(TextChunkStart):
    """Conversation chunk start model.

    Extends TextChunkStart to include client and user input information for
    conversation stream processing.
    """

    def __init__(self, request_id: str, node_name: str, dag: DirectedAcyclicGraph, client_name: str, user_input: str):
        """Initialize the conversation chunk start.

        Args:
            request_id (str):
                Unique identifier for the request.
            node_name (str):
                Name of the processing node.
            dag (DirectedAcyclicGraph):
                Directed acyclic graph for workflow management.
            client_name (str):
                Name of the client that generated the input.
            user_input (str):
                Original user input text for the conversation.
        """
        TextChunkStart.__init__(self, request_id, node_name, dag)
        self.client_name = client_name
        self.user_input = user_input


class ConversationChunkBody(TextChunkBody):
    """Conversation chunk body model.

    Extends TextChunkBody to handle conversation text data within a stream.
    Inherits all functionality from the base TextChunkBody class.
    """

    pass


class ConversationChunkEnd(TextChunkEnd):
    """Conversation chunk end model.

    Extends TextChunkEnd to handle conversation stream completion. Inherits all
    functionality from the base TextChunkEnd class.
    """

    pass


class RejectChunkStart(TextChunkStart):
    """Reject chunk start model.

    Extends TextChunkStart to handle rejection stream initialization. Inherits
    all functionality from the base TextChunkStart class.
    """

    pass


class RejectChunkBody(TextChunkBody):
    """Reject chunk body model.

    Extends TextChunkBody to handle rejection text data within a stream.
    Inherits all functionality from the base TextChunkBody class.
    """

    pass


class RejectChunkEnd(TextChunkEnd):
    """Reject chunk end model.

    Extends TextChunkEnd to handle rejection stream completion. Inherits all
    functionality from the base TextChunkEnd class.
    """

    pass
