from typing import List, Union

from pydantic import BaseModel

from .process_flow import DirectedAcyclicGraph


class Motion(BaseModel):
    """Motion instruction model for speech-to-motion mapping.

    Contains keywords that link speech content to specific motion animations,
    enabling synchronized motion generation based on speech analysis.
    """

    speech_keywords: str
    motion_keywords: str


class EmotionDelta(BaseModel):
    """Emotion delta model for tracking emotion changes.

    Represents the change in emotion intensity values from a previous state.
    Each delta value can be positive (increase) or negative (decrease) to
    indicate the direction and magnitude of emotion change.
    """

    happiness_delta: int = 0
    sadness_delta: int = 0
    fear_delta: int = 0
    anger_delta: int = 0
    disgust_delta: int = 0
    surprise_delta: int = 0
    shyness_delta: int = 0


class Emotion(BaseModel):
    """Current emotion state model.

    Represents the current emotional state with intensity values for different
    emotions. All emotion values must sum to exactly 100 to represent a
    complete emotional profile.
    """

    Happiness: int = 15
    Sadness: int = 14
    Fear: int = 14
    Anger: int = 14
    Disgust: int = 14
    Surprise: int = 15
    Shyness: int = 14

    def model_post_init(self, __context=None) -> None:
        """Validate that emotion sum equals 100.

        Ensures that the sum of all emotion intensity values equals exactly 100,
        maintaining the constraint that emotions represent a complete profile.

        Raises:
            ValueError:
                If the sum of emotion values does not equal 100.
        """
        total = sum(self.model_dump().values())
        if total != 100:
            raise ValueError(f"Emotion values must sum to 100, got {total}")


class Relationship(BaseModel):
    """Current relationship state model.

    Represents the current state of the relationship between the user and the
    character, including the relationship stage and associated score.
    """

    stage: str = "Stranger"
    score: int = 0


class ReactionLLM(BaseModel):
    """Reaction model from LLM processing.

    Contains the complete reaction data generated by a language model,
    including speech text, emotion state, relationship information, and
    associated motion instructions.
    """

    speech_text: str
    emotion: Emotion
    relationship: Relationship
    motion: List[Motion]


class ReactionDelta(BaseModel):
    """Reaction delta model for tracking reaction changes.

    Represents the changes in reaction state from a previous state, including
    emotion deltas, relationship score changes, and motion instruction updates.
    """

    emotion_delta: EmotionDelta
    relationship_delta: int
    motion: List[Motion]


class Reaction(BaseModel):
    """Reaction model containing character response data.

    Represents a character's reaction to user input, including speech text,
    facial expressions, motion keywords with timing, and emotional state.
    """

    speech_text: str
    label_expression: Union[str, None]
    motion_keywords: Union[List[tuple[int, str]], None]
    face_emotion: Union[str, None]


class ReactionChunkStart:
    """Start chunk for reaction stream processing.

    Represents the beginning of a reaction stream with metadata about the
    processing context. Contains information needed to initialize reaction
    processing pipelines.
    """

    def __init__(self, request_id: str, node_name: str, dag: DirectedAcyclicGraph):
        """Initialize the reaction chunk start.

        Args:
            request_id (str):
                Unique identifier for the request.
            node_name (str):
                Name of the processing node.
            dag (DirectedAcyclicGraph):
                Directed acyclic graph for workflow management.
        """
        self.chunk_type = "start"
        self.request_id = request_id
        self.node_name = node_name
        self.dag = dag


class ReactionChunkBody:
    """Body chunk containing reaction data.

    Represents a segment of reaction data within a stream, containing the
    actual reaction information and metadata about the segment's position.
    """

    def __init__(self, request_id: str, seq_number: int, reaction: Reaction):
        """Initialize the reaction chunk body.

        Args:
            request_id (str):
                Unique identifier for the request.
            seq_number (int):
                Sequence number for ordering chunks, starting from 0.
            reaction (Reaction):
                Reaction object containing character response data.
        """
        self.chunk_type = "body"
        self.request_id = request_id
        self.seq_number = seq_number
        self.reaction = reaction


class ReactionChunkEnd:
    """End chunk signaling completion of reaction stream.

    Represents the end of a reaction stream, used to signal that no more
    reaction data will be sent for the given request.
    """

    def __init__(self, request_id: str):
        """Initialize the reaction chunk end.

        Args:
            request_id (str):
                Unique identifier for the request.
        """
        self.chunk_type = "end"
        self.request_id = request_id
