name: Test

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongodb/mongodb-community-server:7.0-ubi8
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ping: 1})'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin_password

    container:
      image: dockersenseyang/dlp3d_orchestrator:latest
      options: --entrypoint ""

    env:
      MONGODB_HOST: localhost
      MONGODB_PORT: 27017

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Download test input
      run: |
        mkdir -p input
        cd input
        curl -LjO https://github.com/LazyBusyYang/CatStream/releases/download/orchestrator_cicd_files/test_audio_16kHz.wav
        curl -LjO https://github.com/LazyBusyYang/CatStream/releases/download/orchestrator_cicd_files/test_audio_24kHz.wav
        cp test_audio_16kHz.wav test_audio.wav
        cd ..
        ls input -la
    - name: Install project
      run: |
        /opt/venv/bin/pip install .
    - name: Init mongodb
      run: |
        /opt/venv/bin/python tools/setup_mongodb_for_test.py --host mongodb --port 27017 --admin_username admin --admin_password admin_password --web_database web_test --memory_database memory_test --orchestrator_username orchestrator --orchestrator_password orchestrator_password
    - name: Run tests
      run: |
        mkdir -p logs
        PYTHONPATH=/__w/audio2face/audio2face /opt/venv/bin/python -m pytest tests --log-cli-level=ERROR
    - name: Cat pytest log
      run: |
        cat logs/pytest.log